# Generated by Django 3.2.2 on 2022-08-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.TextField(verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_item', models.PositiveBigIntegerField(verbose_name='Cost')),
                ('name_of_product', models.CharField(max_length=300, verbose_name='name')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progect2.manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrders',
            fields=[
                ('fulfill_date', models.PositiveIntegerField(verbose_name='Fulfill Month')),
                ('order_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progect2.clients')),
                ('products', models.ManyToManyField(to='progect2.Products')),
            ],
        ),
    ]
