# Generated by Django 3.2.2 on 2022-08-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account_number', models.IntegerField(max_length=18)),
                ('type_selection', models.CharField(choices=[('c', 'checking account'), ('s', 'savings account')], max_length=1, verbose_name='account type')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date_created', models.DateField()),
                ('account_number', models.ManyToManyField(to='bank.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date_created', models.DateField()),
                ('last_transaction', models.DateField()),
                ('account_number', models.ManyToManyField(to='bank.BankAccount')),
            ],
        ),
    ]
